apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tri-sync-pvc
  namespace: tri
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
